/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.audizio.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.audizio.bean.Cliente;
import sistema.audizio.bean.Financeiro;
import sistema.audizio.dao.DaoCliente;
import sistema.audizio.dao.DaoFinanceiro;

/**
 *
 * @author emerson
 */
public class ListarContas extends javax.swing.JDialog {
    
    /**
     * Creates new form ListarClientes
     */
    private DefaultTableModel modeloTabela;
    DaoCliente daoCliente = new DaoCliente();
    public ListarContas(){
        initComponents();
        carregarTabela("");
        setModal(true);
    }
    public void carregarTabela(String situacao){
      ArrayList<Financeiro> financas = new DaoFinanceiro().consultarFinancas(situacao);
      // System.out.println("Tamanho do array "+clientes.size());
       modeloTabela = (DefaultTableModel) tbListarConta.getModel();
       for(Financeiro f:financas){
           modeloTabela.addRow(new Object[] {f.getId(), f.getCliente(),f.getProcesso(), f.getVencimento(), f.getValor_total(), f.getSituacao()});
           System.out.println(f.getCliente());
        }
           tbListarConta.getTableHeader().setReorderingAllowed(false);   
           
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFiltro = new javax.swing.ButtonGroup();
        ScrollTbListarContas = new javax.swing.JScrollPane();
        tbListarConta = new javax.swing.JTable();
        btVerEditar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();
        labelPesquisa = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        panelFiltro = new javax.swing.JPanel();
        cbTodos = new javax.swing.JRadioButton();
        cbPendentes = new javax.swing.JRadioButton();
        cdQuitados = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbListarConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "PROCESSO", "VENCIMENTO", "VALOR TOTAL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollTbListarContas.setViewportView(tbListarConta);
        if (tbListarConta.getColumnModel().getColumnCount() > 0) {
            tbListarConta.getColumnModel().getColumn(0).setResizable(false);
            tbListarConta.getColumnModel().getColumn(0).setPreferredWidth(-10);
            tbListarConta.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbListarConta.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbListarConta.getColumnModel().getColumn(3).setPreferredWidth(60);
            tbListarConta.getColumnModel().getColumn(4).setPreferredWidth(60);
            tbListarConta.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        btVerEditar.setText("VER/EDITAR");
        btVerEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerEditarActionPerformed(evt);
            }
        });

        btQuitar.setText("QUITAR");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });

        labelPesquisa.setText("PESQUISAR:");

        tfPesquisa.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        panelFiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        grupoFiltro.add(cbTodos);
        cbTodos.setText("TODOS");

        grupoFiltro.add(cbPendentes);
        cbPendentes.setText("PENDENTES");

        grupoFiltro.add(cdQuitados);
        cdQuitados.setText("QUITADOS");

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdQuitados)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTodos)
                    .addComponent(cbPendentes)
                    .addComponent(cdQuitados))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btVerEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ScrollTbListarContas, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(tfPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelPesquisa))
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollTbListarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVerEditar)
                    .addComponent(btQuitar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVerEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerEditarActionPerformed
        System.out.println("Clicando");
        try {
            String idConta;
            idConta = tbListarConta.getValueAt(tbListarConta.getSelectedRow(),0).toString();
            System.out.println("Id Conta: "+idConta);
       
           
            //this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "SELECIONE UM CONTA PARA VER E/OU EDITAR.");
        }
       
       
    }//GEN-LAST:event_btVerEditarActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        DaoCliente dao = new DaoCliente();
        Cliente cliente = new Cliente();
        String idConta;

        String message = "Deseja realmente QUITAR esta CONTA?";
        String title = "Confirmação";

        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            System.out.println("Confirmado!");
            idConta = tbListarConta.getValueAt(tbListarConta.getSelectedRow(),0).toString();

            modeloTabela.removeRow(tbListarConta.getSelectedRow());
            JOptionPane.showMessageDialog(null, "CONTA QUITADA!");

    }//GEN-LAST:event_btQuitarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollTbListarContas;
    private javax.swing.JButton btQuitar;
    private javax.swing.JButton btVerEditar;
    private javax.swing.JRadioButton cbPendentes;
    private javax.swing.JRadioButton cbTodos;
    private javax.swing.JRadioButton cdQuitados;
    private javax.swing.ButtonGroup grupoFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JTable tbListarConta;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
